'use client';
import { useState, type FormEvent } from 'react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import assets from './assets.json';

const about = assets['1430:895'], service = assets['1430:2130'], metrics = assets['1480:4786'], news = assets['1480:5078'], contact = assets['1480:4470'], footer = assets['1430:2461'];
const research = 'This initial stage serves as the foundation for the entire process. A total of 300 enumerators were deployed directly to 88 districts/cities to conduct comprehensive primary data collection. This grassroots approach ensures that the data collected truly reflects the real conditions on the ground, rather than mere assumptions or outdated secondary data. Each enumerator is equipped with standardized data collection methods, ensuring that the results are consistent and comparable across regions, providing a solid basis for the subsequent analysis stage.';
const services = [
 { title:'Research Framework', subtitle:'Market research consultant', icon:service.imgBasilSearchSolid, description:research },
 { title:'Data and Intelligence Analytics', subtitle:'AI digital listening platform', icon:service.imgGroup, description:'Field data is complemented by monitoring digital spaces through an AI digital listening platform. This technology analyzes conversations, sentiments, and emerging trends on social media and online platforms in real-time. The combination of field data and digital data provides a more comprehensive picture — understanding not only what is happening in the real world but also how these issues unfold and are perceived by the public in the digital realm.' },
 { title:'Creative Activation', subtitle:'Creative & community agency', icon:service.imgArcticonsPolarisOffice, description:research },
];
const tags = ['Forum group discussion','In-depth interview','Customer satisfaction','Market segmentation','Demand forecasting'];
function Eyebrow({children}:{children:React.ReactNode}) {return <div className="eyebrow"><span/>{children}</div>;}
function BlueArrow() {return <img src={service.imgAkarIconsArrowRight} width="24" height="24" alt=""/>;}
function WhiteArrow() {return <img src={contact.imgTypcnArrowRight} width="24" height="24" alt=""/>;}
function About() {return <section className="section about" id="about"><div className="about-grid container"><div className="iceberg-wrap"><div className="iceberg" role="img" aria-label="An iceberg showing three connected levels: Research Framework, Data and Intelligence Analytics, and Creative Activation."><div className="water water-top"/><div className="water water-bottom"/><div className="waterline"/>{services.map((s,i)=><div key={s.title} className={`iceberg-label label-${i}`}><div><span>{`0${i+1}`}</span>{s.title}</div><img src={[about.imgLine29,about.imgLine30,about.imgLine31][i]} alt=""/></div>)}<img className="iceberg-art" src={about.imgGroup} width="237" height="428" alt=""/><img className="iceberg-flag" src={about.imgBxsFlagAlt} width="24" height="24" alt=""/></div></div><div className="about-copy"><div><Eyebrow>About Us</Eyebrow><h2>Introduction</h2></div><p><strong>Bathys comes from the Greek word βαθύς </strong>— meaning deep. It is the root of bathyscaphe (depth submarine) and bathymetry (measurement of ocean depths). We apply the same philosophy to data: not just monitoring conversations at the surface, but diving into context, local language, and the real behavior of Indonesian consumers.</p><a className="button" href="#services">Know more about us <WhiteArrow/></a></div></div></section>;}
function Platforms() {const p=assets['1609:1328'];const items=[['X (Twitter)',p.imgDeviconTwitter],['Youtube',p.imgMynauiYoutubeSolid],['Instagram',p.imgGroup],['Threads',p.imgMingcuteThreadsLine],['Facebook',p.imgFormkitFacebook],['Tiktok',p.imgLineiconsTiktok],['News',p.imgIconamoonNewsFill]];return <section className="section platforms"><div className="container platform-box"><p>Providing solutions for best platform</p><div>{items.map(([name,src])=><span key={name}><img src={src} width="32" height="32" alt=""/>{name}</span>)}</div></div></section>;}
function Services() {return <section className="section services" id="services"><img className="service-decoration decoration-one" src={service.imgVector183} width="341" height="812" alt=""/><img className="service-decoration decoration-two" src={service.imgVector184} width="376" height="718" alt=""/><div className="container"><div className="section-heading"><Eyebrow>Our Service</Eyebrow><h2><em>Three</em> units,one <em>ecosystem.</em></h2><p>From field data collection to campaign execution every Navis business unit reinforces the next, vertically.</p></div><Tabs defaultValue="0" className="service-tabs"><TabsList className="service-tab-list" aria-label="Navis business units">{services.map((s,i)=><TabsTrigger key={s.title} value={String(i)} className="service-tab"><span className="tab-icon"><img src={s.icon} width="26" height="26" alt=""/></span><span><b>{s.title}</b><small>{s.subtitle}</small></span></TabsTrigger>)}</TabsList>{services.map((s,i)=><TabsContent key={s.title} value={String(i)} className="service-panel"><div className="service-art"><img src={`/assets/service-${i}.png`} alt={`${s.title} illustration from the Navis design`} width="624" height="400" loading="lazy"/></div><div className="service-copy"><div><p className="service-subtitle">{s.subtitle}</p><h3>{s.title}</h3><p>{s.description}</p></div><div className="tags">{tags.map(t=><span key={t}>{t}</span>)}</div><a href="#contact" className="button light">Learn More <BlueArrow/></a></div></TabsContent>)}</Tabs></div></section>;}
function Metrics() {const stats=[['167M','Active Indonesian social media users'],['17.2%','CAGR global social intelligence'],['USD 165M','Indonesia’s social listening market'],['USD 5.25B','Social commerce Indonesia 2025']];const logos=[['Notion',metrics.imgNotion],['Slack',metrics.imgSlack],['Google Drive',metrics.imgGoogleDrive],['Intercom',metrics.imgIntercom],['Jira',metrics.imgJira],['Dropbox',metrics.imgDropbox],['Stripe',metrics.imgStripe],['Zapier',metrics.imgZapier]];return <section className="section metrics" id="why-us"><div className="container"><div className="metrics-card"><div className="section-heading"><Eyebrow>Why Choose US</Eyebrow><h2>Built to Make a <em>Difference</em></h2><p>We listen, we care, and we deliver making every step simple, seamless, and worthwhile.</p></div><div className="stats">{stats.map(([value,label])=><div key={value}><b>{value}</b><p>{label}</p></div>)}</div><p className="trusted-title">Trusted by Businesses, Proven by Results</p><div className="logo-window"><div className="logo-track">{[0,1,2].map(repeat=><div className="logo-set" key={repeat} aria-hidden={repeat>0?true:undefined}>{logos.map(([name,src])=><img key={name} src={src} alt={repeat===0?name:''} width="64" height="64" loading="lazy"/>)}</div>)}</div></div></div><div className="trial"><img className="trial-lines" src={metrics.imgLineGradient} width="1700" height="1200" alt=""/><div><h2>Start your 7-day free trial</h2><p>Join over 4,000+ company already growing with Us</p></div><div className="trial-actions"><a href="#services">Learn More</a><a className="button" href="#contact">Get Started <WhiteArrow/></a></div></div></div></section>;}
const posts=[
 {date:'20 Jan 2025',image:news.imgImage,title:'Brand Crisis Detection: Spot Issues Before They Escalate',description:'A sudden increase in negative mentions can be an early warning sign of a potential brand crisis. Social media listening helps teams monitor unusual spikes in conversations, identify the source of the issue, and understand how quickly it is spreading.'},
 {date:'19 Jan 2025',image:news.imgImage1,title:'Understanding Sudden Changes in Public Opinion',description:'When positive or negative conversations suddenly increase, there is often a reason behind the change. It could be a product launch, viral post, service disruption, or breaking news.'},
 {date:'18 Jan 2025',image:news.imgImage2,title:'Competitor Monitoring: Know Where You Stand',description:'Understanding what customers say about competitors can reveal valuable insights into the market. By monitoring competitor mentions, brands can identify popular products, recurring complaints, successful campaigns, and changing customer preferences.'},
];
function News() {return <section className="section news" id="news"><div className="container"><div className="news-heading"><div><Eyebrow>News</Eyebrow><h2>Recent blog posts</h2></div><a href="#posts" className="button light">View All Post <BlueArrow/></a></div><div className="posts" id="posts">{posts.map((p,i)=><article className={`post post-${i}`} key={p.title}><img src={p.image} width={i===0?668:320} height={i===0?260:200} alt={p.title} loading="lazy"/><div><time>{p.date}</time><h3>{p.title}</h3><p>{p.description}</p></div></article>)}</div></div></section>;}
function Contact() {const [unit,setUnit]=useState<string|null>('Bathys Research');const [draft,setDraft]=useState('');const [status,setStatus]=useState('');function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const body=`Name: ${data.get('name')}\nCompany: ${data.get('company')}\nEmail: ${data.get('email')}\nUnit: ${unit}\n\n${data.get('needs')}`;const url=`mailto:hello@navis.id?subject=${encodeURIComponent(`Navis enquiry — ${unit}`)}&body=${encodeURIComponent(body)}`;setDraft(url);setStatus('Your email draft is ready. Review and send it in your email app.');window.location.href=url;}
return <section className="section contact" id="contact"><div className="container contact-grid"><aside className="contact-info" style={{backgroundImage:`linear-gradient(#000a,#000a),url(${contact.imgContentContainer})`}}><Eyebrow>Contact Us</Eyebrow><h2>Let’s start diving together.</h2><p>Tell us about your research, listening, or campaign needs — our team will put together a recommendation for the business unit that fits best.</p><dl><div><dt><img src={contact.imgMail} width="20" height="20" alt=""/>Email</dt><dd><a href="mailto:hello@navis.id">hello@navis.id</a><small>Response within 1 business day</small></dd></div><div><dt><img src={contact.imgPhone} width="20" height="20" alt=""/>Phone</dt><dd><a href="tel:+622150501234">+62 21 5050 1234</a><small>Mon-Fri from 8am to 5pm.</small></dd></div><div><dt><img src={contact.imgMapPin} width="20" height="20" alt=""/>Office</dt><dd>South Jakarta, Indonesia<small>Jabodetabek field base station</small></dd></div></dl></aside><div className="contact-form"><form onSubmit={submit}><div className="form-heading"><h2>Get in touch</h2><p>Our friendly team would love to hear from you.</p></div><div className="form-fields"><div className="form-row"><label htmlFor="name">Full Name<Input id="name" name="name" placeholder="Full Name" autoComplete="name" required maxLength={120}/></label><label htmlFor="company">Company<Input id="company" name="company" placeholder="Brand / Company" autoComplete="organization" required maxLength={160}/></label></div><label htmlFor="email">Email<Input id="email" name="email" type="email" placeholder="you@company.com" autoComplete="email" required maxLength={254}/></label><label htmlFor="unit">Unit of Interest</label><Select value={unit} onValueChange={setUnit} items={['Bathys Research','Data and Intelligence Analytics','Creative Activation'].map(value=>({value,label:value}))}><SelectTrigger id="unit" className="unit-select"><SelectValue/></SelectTrigger><SelectContent className="unit-options">{['Bathys Research','Data and Intelligence Analytics','Creative Activation'].map(value=><SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select><label htmlFor="needs">Tell us about your needs<Textarea id="needs" name="needs" required maxLength={3000} rows={5}/></label></div><Button type="submit" className="button send-request">Send Request <WhiteArrow/></Button><p className="form-note">Opens a draft in your email app.</p>{status&&<p role="status" className="form-status">{status} <a href={draft}>Open email draft</a></p>}</form></div></div></section>;}
function Footer() {return <footer className="footer"><div className="container footer-content"><a className="logo" href="#home" aria-label="Back to top"><img src={footer.imgPlayground} width="40" height="40" alt=""/><img src={footer.imgNavis} width="75" height="19" alt="NAVIS"/></a><p>Building Indonesia's most comprehensive marketing data ecosystem · © 2026</p><div className="social-icons">{[footer.imgSocialIcon,footer.imgGroup,footer.imgSocialIcon1,footer.imgSocialIcon2,footer.imgLozenge].map((src,i)=><img key={src} src={src} width="24" height="24" alt={['Facebook','Instagram','LinkedIn','Twitter','Youtube'][i]}/>)}</div></div></footer>;}
export default function Sections(){return <><About/><Platforms/><Services/><Metrics/><News/><Contact/><Footer/></>;}
