import assets from '../assets.json';

const images = assets['1480:5078'];
export const posts = [
  { slug: 'brand-crisis-detection', date: '20 Jan 2025', isoDate: '2025-01-20', image: images.imgImage, title: 'Brand Crisis Detection: Spot Issues Before They Escalate', description: 'A sudden increase in negative mentions can be an early warning sign of a potential brand crisis. Social media listening helps teams monitor unusual spikes in conversations, identify the source of the issue, and understand how quickly it is spreading.', sections: [] },
  { slug: 'understanding-sudden-changes-in-public-opinion', date: '19 Jan 2025', isoDate: '2025-01-19', image: images.imgImage1, title: 'Understanding Sudden Changes in Public Opinion', description: 'When positive or negative conversations suddenly increase, there is often a reason behind the change. It could be a product launch, viral post, service disruption, or breaking news.', sections: [
    { heading: 'Membaca Perubahan Percakapan', paragraphs: ['Opini publik dapat berubah ketika pengalaman baru, berita, atau percakapan yang ramai mengubah cara orang memandang sebuah brand. Lonjakan jumlah mention menjadi titik awal untuk memahami perubahan tersebut, tetapi belum menjelaskan penyebabnya.', 'Bandingkan percakapan terbaru dengan pola yang biasanya muncul. Perhatikan topik, kanal, dan pengalaman yang paling sering disebut agar tim dapat membedakan perubahan sementara dari masalah yang terus berkembang.'] },
    { heading: 'Memahami Penyebab dan Konteks', paragraphs: ['Telusuri kapan percakapan mulai meningkat dan peristiwa apa yang mendahuluinya. Peluncuran produk, perubahan layanan, atau unggahan yang banyak dibagikan dapat menghasilkan reaksi yang berbeda di setiap kelompok audiens.', 'Baca contoh percakapan secara langsung. Label sentimen saja tidak selalu menangkap sarkasme, bahasa lokal, dan maksud di balik komentar. Gabungkan hasil pemantauan dengan pertanyaan yang masuk ke tim layanan pelanggan.'] },
    { heading: 'Mengubah Temuan Menjadi Respons', paragraphs: ['Tentukan respons berdasarkan kebutuhan yang terlihat dalam percakapan. Pertanyaan berulang mungkin memerlukan penjelasan yang lebih mudah ditemukan, sedangkan keluhan layanan perlu diteruskan kepada tim yang dapat menyelesaikannya.', 'Setelah mengambil tindakan, pantau apakah topik dan nada percakapan berubah. Catat apa yang dilakukan dan apa yang masih belum terjawab sebagai bahan evaluasi berikutnya.'] },
  ] },
  { slug: 'competitor-monitoring', date: '18 Jan 2025', isoDate: '2025-01-18', image: images.imgImage2, title: 'Competitor Monitoring: Know Where You Stand', description: 'Understanding what customers say about competitors can reveal valuable insights into the market. By monitoring competitor mentions, brands can identify popular products, recurring complaints, successful campaigns, and changing customer preferences.', sections: [
    { heading: 'Mulai dengan Pertanyaan yang Jelas', paragraphs: ['Pemantauan kompetitor membantu brand memahami pilihan dan harapan pelanggan. Tentukan terlebih dahulu apa yang ingin dipelajari, seperti pengalaman layanan, persepsi harga, atau fitur produk yang sering dibicarakan.', 'Pilih kompetitor dan kanal yang relevan dengan audiens Anda. Gunakan periode pemantauan yang sama agar perbandingan tidak dipengaruhi oleh perbedaan waktu atau peristiwa tertentu.'] },
    { heading: 'Bandingkan Pengalaman, Bukan Hanya Angka', paragraphs: ['Jumlah mention menunjukkan seberapa sering brand dibicarakan, tetapi tidak langsung menunjukkan kualitas pengalaman pelanggan. Telusuri tema di balik pujian, pertanyaan, dan keluhan untuk mengetahui apa yang dianggap bernilai.', 'Perhatikan konteks kampanye, peluncuran produk, dan perubahan layanan. Percakapan yang lebih ramai belum tentu berarti pelanggan lebih puas; contoh komentar membantu menjelaskan angka yang terlihat.'] },
    { heading: 'Temukan Peluang yang Relevan', paragraphs: ['Keluhan berulang di pasar dapat menunjukkan kebutuhan yang belum terpenuhi. Bandingkan temuan tersebut dengan kemampuan produk dan layanan sendiri sebelum menentukan prioritas perbaikan.', 'Bagikan ringkasan temuan kepada tim produk, layanan, dan komunikasi. Gunakan pemantauan kompetitor sebagai masukan untuk keputusan, lalu validasi dugaan melalui riset pelanggan dan hasil tindakan yang dilakukan.'] },
  ] },
];
export type BlogPost = (typeof posts)[number];
